name: ReactJs CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [16.16.0]
        npm: [8.16.0]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
        env:
          HUSKY: 0
      - name: Eslint validation packages
        run: npm run lint:es:ci
