name: Release CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [16.16.0]
        npm: [8.16.0]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
        env:
          HUSKY: 0
      - name: Eslint validation packages
        run: npm run lint:es:ci

  release:
    needs: build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [16.16.0]
        npm: [8.16.0]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install standard-version
        run: sudo npm i -g standard-version
      - name: Setup GIT user
        uses: fregante/setup-git-user@v1
      - name: 'Release version'
        run: |
          git checkout main
          standard-version --no-verify --releaseCommitMessageFormat="chore: new version released [skip ci]"
          git push --follow-tags origin main
      - name: Merge into develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ github.token }}
